travis:
  secure:
    BINSTAR_TOKEN: UJ3OzoQKxqncApUdXLb7y0IRIlOgKcnVLEzlSP6pqUIFN3+k/9dY4LwErNL2LruU0xg/QbxspkikUEhbjHKHoDY2k6djJPZUeDmTmcvDBvrGnfzA/OeNEriwR6wr8agBVFUT/+pC5V4QkcNvZvA4L0T7h8JwVl7TbhZRqLS2Ezy0Q/Vrw2euO23TKqLuddTE8VByoeCbYucBDWRTkdfXSWp9PiZLdq3pxKshTeul55zGaMmWub07qfvTNhFy81QAZcZC1eF7miwJB8s6fvns4FLEXvdUP9a4UwnCN7NW5LxsxHsNSbOPwT9wKtDV/qTcmivw67GGQTCvH7l20XWD66aGo+V7AxCAZbL4clYghE8VgpYS9aRz+am8ByFdzH31pNIt56fOhMsf4s73WRIfKOQRhcF4wYsF5p0SPTT6NFoIo9vmJqzXbP4Wi+yj1Ba8QbCQU7LEET5APzJvTmSfJH6ITsitc50jtdiEnbpOSSHeZTsVWf7luzHMNwoUHodzuPg4l80ecuRZwF1yo29+cOBDsn3JhBkItpMQoN1RgvapbNBrLsthjFcricIA9hEWaboJlLYExBOg9BBq5OYVyIxhSdDPmzjAGkiZUuJ8RWdCO4NPiUzuozc+eVgZNuwMYQOebpzRzCFQ5b2K7oLB1IcoL42bcsjFIRz7V9bB0+c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
