travis:
  secure:
    BINSTAR_TOKEN: KxK6eW65xUln16QvI5ROT7u6EtHgJJZLhprcuuQDNgU37MxqUPhZc7/hPXihY615dSO2/HEBdb6FIGonemRa6aIj9ahmarSnrWjxkIC18ZDRtuyvwnZos3cf0rhORfawgH5HA/0JQTRBjfcLyW4SEjhXEQK/UQivVcf0P+cfJCEnKQt3rkvYuCFYmPcXP/uN5PVfL+suqh0wZwwhG09Vo3VUZbJG5QvqRNu7ZORp+bl62dXgUp41K7+xfOTyeh8F6Ih/+2zQ0JD3zWkcWio7gch9RxeMa5IofVnk1tD35/5Q6C9jDEOtP8Pt7+JHoB2ThShwDbbbAULN2+Fj8IC3GnXCnLbYerLa1m3GOeAQjhsvOEEm4xm5k/xbRRvculk0No8isqjIxWW0e4xnURZD2lFXKHm1Rj6E9sXM/aN7WAFnPR1uHf1lInvbwT9LP7IDgnW/8oh9jJRBdgcJFhToRDx6i+dhoxeOlGvYEMFwxeN/IlEmHyK+Smzvaa4sno8wZZ9X9hsXrEkTYiVPA7mSxQrqIT7ROX6v2rmWBxn0SJU/HwB/t7AqgLL1gq0PmXqFfRgyvnw4zg0kBILT3WKExDl7nvRAlnJlkn0ZSplivwq8IwVnEkpCv1DLNCPxuzuoNLvQ3LWSbkheRcJJC0TR7vrSOiepSezrYtRoxpNT+4Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
